@startuml

interface connector {
}

interface connector_api {
}

interface ocpp_api
interface hlc_api

interface fsm
interface metering
interface safety
interface pilot
interface relay
interface pp
interface server
interface adc
interface pwm
interface uart

class charger {
}

pilot --> adc
pilot --> pwm
relay --> pwm
metering --> uart

hlw8112 ..|> metering

adc122s051 ..|> adc

iec61851 --> pilot
iec61851 --> relay
iec61851 --> pp

connector --> fsm
connector --> iec61851
connector "1" *-- "many" safety
connector --> metering
free_connector ..|> connector
free_connector ..|> connector_api
ocpp_connector ..|> connector
ocpp_connector ..|> ocpp_api
hlc_connector ..|> connector
hlc_connector ..|> hlc_api

ocpp_api --|> connector_api
hlc_api --|> ocpp_api

free_fsm ..|> fsm
ocpp_fsm ..|> fsm

ocpp_connector ---> ocpp
ocpp_connector ---> csms
csms --> websocket
websocket ..|> server

hlc_connector --> plc

input_power ..|> safety
output_power ..|> safety
temperature ..|> safety
emergency_stop ..|> safety

charger "1" *--- "many" connector

@enduml
